language: python
sudo: required
dist: trusty
matrix:
  include:
    - python: 3.5
    - python: 3.6
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
before_install:
  - export CC="gcc-4.9"
  - export CXX="g++-4.9"
install:
  - pip install numpy
  - pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
  - pip install torch-scatter torch-sparse torch-cluster==1.4.3-alpha1 torch-spline-conv
  - pip install cython && pip install gdist
  - pip install pycodestyle
  - pip install flake8
  - pip install codecov
script:
  - pycodestyle .
  - flake8 .
  - python setup.py install
  - python setup.py test
  - cd docs && pip install -r requirements_1.txt && make clean && make html && cd ..
after_success:
  - codecov
notifications:
  email: false
